
-- CORRECCIÓN RÁPIDA: Otorgar permisos a las tablas existentes
-- Ejecuta esto en el SQL Editor de Supabase si las tablas ya existen

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL SEQUENCES IN SCHEMA public TO anon, authenticated;

-- Deshabilitar RLS temporalmente para testing
ALTER TABLE IF EXISTS usuarios DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS insumos DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS categorias DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS proveedores DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS ordenes DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS orden_detalle DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS recepciones DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS recepcion_detalle DISABLE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS kardex DISABLE ROW LEVEL SECURITY;
